language: python
sudo: false
cache: pip

python:
  - "2.7"
  - "3.6"

install:
  - pip install 'requests>=2.8.14'
  - pip install 'pandas>=0.22'
  - pip install 'lxml>=4.2.1'
  - pip install coveralls
  - pip install vcrpy
  - pip install vcrpy-unittest

script:
  - nosetests -v --with-coverage --cover-package=pytaxize
