language: python
sudo: false

python:
  - "2.7"
  - "3.4"

install:
  - pip install 'requests>=2.7'
  - pip install 'pandas>=0.19.2'
  - pip install 'lxml>=3.7.3'
  - pip install coveralls

script:
  - nosetests -v --with-coverage --cover-package=pytaxize
