language: python
cache: pip
os: linux

python:
  - "2.7"
  - "3.6"
  - "3.8"

install:
  - pip install -r requirements.txt

install:
  - pip install 'pandas>=0.22'
  - pip install codecov
  - pip install vcrpy
  - pip install vcrpy-unittest
  - pip install pytest
  - pip install pytest-cov

script:
  - pytest --verbose --disable-warnings --cov=pytaxize/ --ignore setup.py

after_success:
  - codecov
